
SELECT *
from worker_details;

SELECT WD.WORKER_ID,WD.FIRST_NAME+' '+WD.LAST_NAME AS 'Employee Name' , WD.DEPARTMENT
FROM WORKER_DETAILS WD
JOIN
TITLE T
ON (WD.WORKER_ID=T.WORKER_REF_ID)
WHERE T.WORKER_TITLE LIKE 'Consultant';


SELECT TOP 4 FIRST_NAME+' '+LAST_NAME AS 'Employee Name', SALARY,DEPARTMENT
FROM WORKER_DETAILS
WHERE (SALARY) IN (SELECT MAX(SALARY) AS 'SAL'
					FROM WORKER_DETAILS
					GROUP BY DEPARTMENT);


WITH HIGHEST AS (
SELECT DEPARTMENT, FIRST_NAME, LAST_NAME,SALARY, DENSE_RANK() 
OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC)
AS RowNum
FROM WORKER_DETAILS
)
SELECT DEPARTMENT , FIRST_NAME+' '+LAST_NAME AS 'Employee Name',SALARY
FROM HIGHEST
WHERE ROWNUM=1;

					